import React, { useState, useEffect } from 'react'
import { useSelector, useDispatch } from 'react-redux'
import Head from 'next/head'
import Link from 'next/link'
import cn from 'classnames'
import { updateProfile } from '../../store/features/auth/AuthSlice'

function index() {
  const { currentUser } = useSelector((state) => state.auth)


  const dispatch = useDispatch()

  

  return (
    <div className="container mx-auto">
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mt-3 mb-3 flex h-screen flex-col md:flex-row md:space-x-2">
        <div className="lg:w-3/10 ml-3 mr-3 p-4 md:w-2/6">
          <div className="py-6 px-4 sm:px-6">
            <div className="flex text-base font-medium text-gray-900">
              <ul role="list" className="w-full justify-between">
                <li className="border-b border-gray-300 py-2">
                  <Link href="/profile">
                    <a className="font-medium text-indigo-600 hover:text-indigo-500">
                      Profile<span aria-hidden="true"> &rarr;</span>
                    </a>
                  </Link>
                </li>
                <li className="border-b border-gray-300 py-2">
                  <Link href="/profile/orders">
                    <a className="font-medium text-indigo-600 hover:text-indigo-500">
                      My Orders<span aria-hidden="true"> &rarr;</span>
                    </a>
                  </Link>
                </li>
              </ul>
            </div>
          </div>
        </div>

        <div className="lg:w-7/10 ml-3 mr-3 rounded-md border bg-white p-4 shadow-md md:w-4/6 xl:px-20">
          <div className="mt-8">
          <div className="relative overflow-x-auto shadow-md sm:rounded-lg">
              <table className="w-full text-left text-sm text-gray-500 dark:text-gray-400">
                <thead className="bg-gray-50 text-xs uppercase text-gray-700 dark:bg-gray-700 dark:text-gray-400">
                  <tr>
                    <th scope="col" className="px-6 py-3">
                      
                    </th>
                    <th scope="col" className="px-6 py-3">
                      
                    </th>
                  </tr>
                </thead>
                <tbody>
                    <tr className="border-b bg-white dark:border-gray-700 dark:bg-gray-800">
                      <th
                        scope="row"
                        className="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap"
                      >
                        First Name
                      </th>
                      <td className="px-6 py-4">{currentUser.first_name}</td> 
                    </tr>
                    <tr className="border-b bg-white dark:border-gray-700 dark:bg-gray-800">
                      <th
                        scope="row"
                        className="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap"
                      >
                        Last Name
                      </th>
                      <td className="px-6 py-4">{currentUser.last_name}</td> 
                    </tr>
                    
                    
                    <tr className="border-b bg-white dark:border-gray-700 dark:bg-gray-800">
                      <th
                        scope="row"
                        className="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap"
                      >
                        Email
                      </th>
                      <td className="px-6 py-4">{currentUser.email}</td> 
                    </tr>
                   
                    
                    
                    
                    
                                   
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default index
