# Generated by Django 4.0.4 on 2022-08-13 00:22

import autopart.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_measurement.models
import measurement.measures.mass
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Category Name')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='autopart/category/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Category Image')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('mptt_level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='autopart.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=autopart.models.upload_product_image, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Product Image')),
                ('sku', models.CharField(max_length=255, unique=True, verbose_name='Stock Keeping Unit')),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='Stock')),
                ('moq', models.IntegerField(blank=True, null=True, verbose_name='Minimum Order Quantity')),
                ('weight', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.mass.Mass, null=True)),
                ('price_net', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('price_discounted', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Discounted Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_new', models.BooleanField(default=False, verbose_name='New')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='autopart.category', verbose_name='Category')),
                ('compatible_cars', models.ManyToManyField(blank=True, related_name='products', to='auto.car', verbose_name='Compatible Cars')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Brand Name')),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=autopart.models.upload_productbrand_image, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Brand Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(blank=True, help_text='example: Original', max_length=32, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Product Brand',
                'verbose_name_plural': 'Product Brands',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Specification')),
            ],
            options={
                'verbose_name': 'Product Specification',
                'verbose_name_plural': 'Product Specifications',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecificationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='autopart.product')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='autopart.productspecification', verbose_name='Specification')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.ForeignKey(blank=True, help_text='example : Boscho', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbrand_products', to='autopart.productbrand', verbose_name='Product Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='account.supplieruser', verbose_name='Supplier'),
        ),
        migrations.CreateModel(
            name='OEMCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=64, verbose_name='Brand Name')),
                ('code', models.CharField(max_length=64, verbose_name='OEM Code')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oem_codes', to='autopart.product')),
            ],
            options={
                'verbose_name': 'OEM Code',
                'verbose_name_plural': 'OEM Codes',
            },
        ),
    ]
