import React from 'react'
import Head from 'next/head'
import Script from 'next/script'


function LayoutHelper({ children }) {
  return (
    <div className="min-h-screen bg-gray-100">
      <Head>
        <title>Turkey Auto Parts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.0.2/tailwind.min.css"></link>
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Scada" media="all"></link>
      </Head>

      <main>
        {children}
      </main>

      <Script src="https://cdnjs.cloudflare.com/ajax/libs/alpinejs/2.8.0/alpine.js" />
    </div>
  )
}

export default LayoutHelper
