import React from 'react'
import BrandList from '../../components/BrandList'
import Head from 'next/head'

function BrandListPage(props) {
  return (
    <div className="container mx-auto">
      <Head>
        <title>Cars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mt-3 mb-3 h-screen rounded-lg border bg-white shadow-lg">

        <BrandList brands={props.brands} />
      </div>
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch('http://127.0.0.1:8000/api/auto/brands/')
  const brands = await res.json()

  return {
    props: {
      brands,
    },
  }
}

export default BrandListPage
