import React, { useState, useEffect } from 'react'
import { useSelector, useDispatch } from 'react-redux'
import CartSingle from '../components/CartSingle'
import Head from 'next/head'
import Link from 'next/link'
import cn from 'classnames'
import { getCartTotal } from '../store/features/cart/cartSlice'

function cart() {
  const { cartItems, subtotalPrice } = useSelector((state) => state.cart)
  const dispatch = useDispatch()

  useEffect(() => {
    dispatch(getCartTotal())
  }, [cartItems])

  return (
    <div className="container mx-auto">
      <Head>
        <title>Shopping Cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mt-3 mb-3 flex h-screen flex-col md:flex-row md:space-x-2">
        <div className="lg:w-6/10 ml-3 mr-3 rounded-md border bg-white p-4 shadow-md md:w-4/6 xl:px-20">
          <div class="mt-8">
            <div class="flow-root">
              {cartItems.length <= 0 && (
                <div
                  class="mb-3 inline-flex w-full items-center rounded-lg bg-gray-300 py-5 px-6 text-base text-gray-800"
                  role="alert"
                >
                  <svg
                    aria-hidden="true"
                    focusable="false"
                    data-prefix="fas"
                    data-icon="info-circle"
                    class="mr-2 h-4 w-4 fill-current"
                    role="img"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 512 512"
                  >
                    <path
                      fill="currentColor"
                      d="M256 8C119.043 8 8 119.083 8 256c0 136.997 111.043 248 248 248s248-111.003 248-248C504 119.083 392.957 8 256 8zm0 110c23.196 0 42 18.804 42 42s-18.804 42-42 42-42-18.804-42-42 18.804-42 42-42zm56 254c0 6.627-5.373 12-12 12h-88c-6.627 0-12-5.373-12-12v-24c0-6.627 5.373-12 12-12h12v-64h-12c-6.627 0-12-5.373-12-12v-24c0-6.627 5.373-12 12-12h64c6.627 0 12 5.373 12 12v100h12c6.627 0 12 5.373 12 12v24z"
                    ></path>
                  </svg>
                  Shopping Cart is Empty!
                </div>
              )}
              <ul role="list" class="-my-6 divide-y divide-gray-200">
                {cartItems.map((item) => (
                  <CartSingle product_element={item} key={item.id} />
                ))}
              </ul>
            </div>
          </div>
        </div>

        <div className="lg:w-4/10 ml-3 mr-3 p-4 md:w-2/6">
          <div className="border-t border-gray-200 py-6 px-4 sm:px-6">
            <div className="flex justify-between text-base font-medium text-gray-900">
              <p>Subtotal</p>
              <p>${subtotalPrice}</p>
            </div>
            <p className="mt-0.5 text-sm text-gray-500">
              Shipping and taxes calculated at checkout.
            </p>
            <div className="mt-6">
              <Link href="/checkout">
                <a
                  className={cn(
                    cartItems.length <= 0
                      ? 'cursor-not-allowed  bg-gray-500'
                      : 'bg-indigo-600 hover:bg-indigo-700',
                    'flex items-center justify-center rounded-md border border-transparent px-6 py-3 text-base font-medium text-white shadow-sm'
                  )}
                >
                  Checkout
                </a>
              </Link>
            </div>
            <div className="mt-6 flex justify-center text-center text-sm text-gray-500">
              <p>
                or{' '}
                <Link href="/products">
                  <a className="font-medium text-indigo-600 hover:text-indigo-500">
                    Continue Shopping<span aria-hidden="true"> &rarr;</span>
                  </a>
                </Link>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default cart
