import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from '../components/Hero'
import HomeBrandSection from '../components/HomeBrandSection'
import Banner from '../components/Banner'
import CtaSection from '../components/CtaSection'
import HomeLastArticles from '../components/HomeLastArticles'
import Logos from '../components/Logos'
import React from 'react'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />

      <HomeBrandSection />

      <CtaSection
        main_text="Ready to dive in?"
        secondary_text="Start your free trial today."
        left_text="Get started"
        left_path="/"
        right_text="Learn more"
        right_path="/"
      />

      <HomeLastArticles />
      <Logos />

      <Banner
        mobile="We announced a new product!"
        large="Big news! We're excited to announce a brand new product."
        path="/deneme"
        action_text="Learn more"
      />

      
    </>
  )
}
