import React from 'react'
import Head from 'next/head'
import ProductList from '../../components/ProductList'

function ProductDetailPage(props) {
  const previous_btn = props.product_list.previous
  const next_btn = props.product_list.next
  const page_count = props.product_list.count
  const product_list = props.product_list.results

  return (
    <div className="container mx-auto">
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mt-3 mb-3 h-screen flex flex-col md:flex-row md:space-x-2">
        <div className="sm:w-1/5">SIDEBAR</div>
        <div className="rounded-md border bg-white p-4 shadow-md sm:w-4/5 xl:px-20">
          
          <ProductList products={product_list} />
        </div>
      </div>
    </div>
  )
}

export default ProductDetailPage

export const getServerSideProps = async (context) => {
  const { params, query } = context

  let page = 1
  let category = ''

  if (query['page'] !== undefined) {
    page = query['page']
  }

  if (query['category'] !== undefined) {
    category = query['category']
  }

  const car = query['car_id']

  const res = await fetch(
    `http://127.0.0.1:8000/api/autopart/product/?category=${category}&compatible_cars__id=${car}&page=${page}`
  )

  const product_list = await res.json()

  return {
    props: {
      product_list,
    },
  }
}
